import Image from "next/image";
import Link from "next/link";

const cards = [
  ["01", "Our story", "Since 2013, Circle Group has been building pathways from education to work as a women-led social enterprise. In 2025 we also registered as a foundation, so today we can invest in young people directly as well as prepare them for the work ahead."],
  ["02", "Our focus", "We design every program around the barriers young women in underserved communities face when moving into work."],
  ["03", "Our reach", "We work with schools, youth associations, employers, and development organisations to turn training into opportunity."],
];

export default function About() { return <>
  <section className="bg-sand-light py-16 md:py-24"><div className="container-page grid gap-12 lg:grid-cols-[1.08fr_.92fr] lg:items-end"><div><span className="eyebrow text-forest">About Circle Group</span><h1 className="mt-5 max-w-3xl font-display text-5xl font-medium leading-[.98] text-ink sm:text-7xl">Talent is everywhere. Opportunity should be too.</h1><p className="mt-8 max-w-2xl text-lg leading-relaxed text-ink/75">Circle Group creates practical pathways from education to meaningful work. We equip young people with life skills, professional knowledge, networks and career preparation, with a strong focus on young women.</p></div><div className="relative aspect-[4/4.4] overflow-hidden rounded-t-[7rem] rounded-bl-[2rem]"><Image src="/img/new/photo_45_2026-03-03_11-10-37.jpg" alt="Young people taking part in Circle Group training" fill className="object-cover" /></div></div></section>
  <section className="bg-forest py-16 text-white md:py-24"><div className="container-page"><div className="grid gap-px overflow-hidden rounded-[2rem] border border-white/15 bg-white/15 md:grid-cols-3">{cards.map(([number,title,text]) => <article key={number} className="bg-forest p-8 md:p-10"><span className="eyebrow text-amber">{number}</span><h2 className="mt-8 font-display text-3xl">{title}</h2><p className="mt-4 leading-relaxed text-white/75">{text}</p></article>)}</div></div></section>
  <section className="bg-sand py-20 md:py-28"><div className="container-page grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><span className="eyebrow pt-2 text-leaf">The Circle Group approach</span><div><h2 className="max-w-3xl font-display text-4xl leading-tight text-ink sm:text-5xl">Training, readiness, research, and partnerships work together.</h2><p className="mt-7 max-w-2xl text-lg leading-relaxed text-ink/75">These are not separate programs. Research shows us where the gaps are. Training and work readiness close them. Partnerships turn preparation into employment. What we learn goes back into the next program.</p></div></div></section>
  <section className="bg-[#e5efd0] py-20 md:py-28"><div className="container-page grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><span className="eyebrow pt-2 text-forest">Our commitment</span><div><h2 className="font-display text-4xl leading-tight text-ink sm:text-5xl">Trust comes first.</h2><p className="mt-6 max-w-3xl text-lg leading-relaxed text-ink/75">Every young person who walks through our doors is someone’s daughter, someone’s responsibility, before she is ever a participant. That shapes how we design everything we do: trained staff at every touchpoint, clear boundaries in every relationship, and a standing commitment that no young person’s safety is ever the price of a good outcome. Safeguarding is the first thing we build and the thing we protect hardest.</p><Link href="/policies#safeguarding" className="mt-8 inline-flex items-center gap-2 border-b-2 border-leaf pb-1 text-sm font-bold text-forest">Read our safeguarding policy <span>→</span></Link></div></div></section>
  <section className="bg-sand-light py-20"><div className="container-page flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><span className="eyebrow text-leaf">Our people</span><h2 className="mt-4 max-w-xl font-display text-4xl text-ink">The people doing the work behind every opportunity.</h2></div><div><Link href="/team" className="inline-block rounded-full bg-forest px-7 py-3.5 text-sm font-semibold text-white">Meet the team</Link><p className="mt-4 text-sm text-ink/70">Want to join us? <Link href="/work-with-us#careers" className="font-semibold text-leaf underline">See open roles →</Link></p></div></div></section>
</>; }
